### Final Assignment for DS Tools for PH 
This assignment will examine the data file 'Daily change in cases by PHU' 

This assignment will demonstrate the process of using Git, Jupyter Notbooks and GitHub to make the analysis reproducible and transparent. 

First we will load the python library and connect to the data.

In [10]:
import pandas as pd
import matplotlib as plt
filename = 'DailyChangeinCasesbyPHU.csv'
daily_covid_cases = pd.read_csv(filename)
daily_covid_cases.head()

,_id,Date,Algoma_District,Brant_County,Chatham_Kent,Durham_Region,Eastern_Ontario,Grey_Bruce,Haldimand_Norfolk,Haliburton_Kawartha_Pine_Ridge,...,Simcoe_Muskoka_District,Southwestern,Sudbury_and_District,Thunder_Bay_District,Timiskaming,Toronto,Wellington_Dufferin_Guelph,Windsor_Essex_County,York_Region,Total
0,1,2020-01-23T00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,2
1,2,2020-01-24T00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,3,2020-01-25T00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,2020-01-26T00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,2020-01-27T00:00:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Now to examine this dataset though basic descriptive analysis.

In [3]:
# Determine the number of days included in the dataset
len(daily_covid_cases)

1595

In [4]:
# Examine the dataset types
daily_covid_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1595 entries, 0 to 1594
Data columns (total 37 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   _id                             1595 non-null   int64
 1   Date                            1595 non-null   object
 2   Algoma_District                 1595 non-null   int64
 3   Brant_County                    1595 non-null   int64
 4   Chatham_Kent                    1595 non-null   int64
 5   Durham_Region                   1595 non-null   int64
 6   Eastern_Ontario                 1595 non-null   int64
 7   Grey_Bruce                      1595 non-null   int64
 8   Haldimand_Norfolk               1595 non-null   int64
 9   Haliburton_Kawartha_Pine_Ridge  1595 non-null   int64
 10  Halton_Region                   1595 non-null   int64
 11  City_of_Hamilton                1595 non-null   int64
 12  Hastings_Prince_Edward          1595 non-null   int64
 13  Huron_Perth                     1595 non-null   int64
 14  KFLA                            1595 non-null   int64
 15  Lambton_County                  1595 non-null   int64
 16  Leeds_Grenville_Lanark          1595 non-null   int64
 17  Middlesex_London                1595 non-null   int64
 18  Niagara_Region                  1595 non-null   int64
 19  North_Bay_Parry_Sound_District  1595 non-null   int64
 20  Northwestern                    1595 non-null   int64
 21  City_of_Ottawa                  1595 non-null   int64
 22  Peel_Region                     1595 non-null   int64
 23  Peterborough_County_City        1595 non-null   int64
 24  Porcupine                       1595 non-null   int64
 25  Waterloo_Region                 1595 non-null   int64
 26  Renfrew_County_and_District     1595 non-null   int64
 27  Simcoe_Muskoka_District         1595 non-null   int64
 28  Southwestern                    1595 non-null   int64
 29  Sudbury_and_District            1595 non-null   int64
 30  Thunder_Bay_District            1595 non-null   int64
 31  Timiskaming                     1595 non-null   int64
 32  Toronto                         1595 non-null   int64
 33  Wellington_Dufferin_Guelph      1595 non-null   int64
 34  Windsor_Essex_County            1595 non-null   int64
 35  York_Region                     1595 non-null   int64
 36  Total                           1595 non-null   int64
dtypes: int64(36), object(1)
memory usage: 461.2+ KB

In [5]:
# Checking summary statistics for the dataframe
daily_covid_cases.describe()

,_id,Algoma_District,Brant_County,Chatham_Kent,Durham_Region,Eastern_Ontario,Grey_Bruce,Haldimand_Norfolk,Haliburton_Kawartha_Pine_Ridge,Halton_Region,...,Simcoe_Muskoka_District,Southwestern,Sudbury_and_District,Thunder_Bay_District,Timiskaming,Toronto,Wellington_Dufferin_Guelph,Windsor_Essex_County,York_Region,Total
count,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,...,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000,1595.000000
mean,798.000000,8.904075,10.083386,7.677743,49.208150,14.240752,8.479624,7.747335,9.370533,38.674608,...,39.368652,12.564890,15.407524,13.133542,2.309091,252.240125,18.643260,35.556113,87.914734,1078.521630
std,460.581155,14.931091,18.075159,13.628711,97.759906,29.247972,15.098009,13.885650,16.807606,84.068242,...,69.977166,20.416308,24.877379,20.578682,4.458551,439.008268,33.478734,57.362272,161.263320,1778.653499
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,399.500000,0.000000,1.000000,0.000000,7.000000,2.000000,1.000000,1.000000,1.000000,5.000000,...,6.000000,1.000000,1.000000,1.000000,0.000000,42.000000,3.000000,5.000000,13.000000,197.500000
50%,798.000000,3.000000,5.000000,3.000000,23.000000,7.000000,4.000000,3.000000,4.000000,17.000000,...,20.000000,6.000000,6.000000,5.000000,0.000000,117.000000,9.000000,17.000000,41.000000,563.000000
75%,1196.500000,10.000000,12.000000,10.000000,48.500000,15.000000,9.000000,9.000000,11.000000,40.000000,...,44.000000,16.000000,20.000000,16.000000,3.000000,273.500000,20.500000,43.000000,94.000000,1260.500000
max,1595.000000,137.000000,208.000000,165.000000,991.000000,366.000000,199.000000,158.000000,174.000000,943.000000,...,770.000000,248.000000,238.000000,191.000000,43.000000,4706.000000,523.000000,586.000000,1794.000000,19511.000000

In [9]:
# Identify the dates with the highest and lowest case counts
daily_covid_cases['Total'].min()

0

In [8]:
daily_covid_cases['Total'].max()

19511